import {generateKeys, generateLocalization} from '../utils'

const countries = generateLocalization('countries', generateKeys({
  af: {value: 'AF', label: 'Afghanistan', forbidden: true, region: 'asiaAndPacific'},
  ax: {value: 'AX', label: 'Aland Islands', region: 'europe'},
  al: {value: 'AL', label: 'Albania', region: 'europe'},
  dz: {value: 'DZ', label: 'Algeria', forbidden: true, region: 'arabStates'},
  as: {value: 'AS', label: 'American Samoa', region: 'asiaAndPacific'},
  ad: {value: 'AD', label: 'Andorra', region: 'europe'},
  ao: {value: 'AO', label: 'Angola', region: 'africa'},
  ai: {value: 'AI', label: 'Anguilla', region: 'southLatinAmerica'},
  aq: {value: 'AQ', label: 'Antarctica', region: 'asiaAndPacific'},
  ag: {value: 'AG', label: 'Antigua And Barbuda'},
  ar: {value: 'AR', label: 'Argentina', region: 'southLatinAmerica'},
  am: {value: 'AM', label: 'Armenia', region: 'europe'},
  aw: {value: 'AW', label: 'Aruba', region: 'southLatinAmerica'},
  au: {value: 'AU', label: 'Australia', region: 'asiaAndPacific'},
  at: {value: 'AT', label: 'Austria', region: 'europe'},
  az: {value: 'AZ', label: 'Azerbaijan', region: 'asiaAndPacific'},
  bs: {value: 'BS', label: 'Bahamas', region: 'southLatinAmerica'},
  bh: {value: 'BH', label: 'Bahrain', region: 'arabStates'},
  bd: {value: 'BD', label: 'Bangladesh', region: 'asiaAndPacific'},
  bb: {value: 'BB', label: 'Barbados', region: 'southLatinAmerica'},
  by: {value: 'BY', label: 'Belarus', region: 'europe'},
  be: {value: 'BE', label: 'Belgium', forbidden: true, region: 'europe'},
  bz: {value: 'BZ', label: 'Belize', region: 'southLatinAmerica'},
  bj: {value: 'BJ', label: 'Benin', region: 'africa'},
  bm: {value: 'BM', label: 'Bermuda', region: 'northAmerica'},
  bt: {value: 'BT', label: 'Bhutan', region: 'asiaAndPacific'},
  bo: {value: 'BO', label: 'Bolivia', region: 'southLatinAmerica'},
  ba: {value: 'BA', label: 'Bosnia And Herzegovina', forbidden: true},
  bw: {value: 'BW', label: 'Botswana', region: 'africa'},
  bv: {value: 'BV', label: 'Bouvet Island', region: 'southLatinAmerica'},
  br: {value: 'BR', label: 'Brazil', region: 'southLatinAmerica'},
  io: {value: 'IO', label: 'British Indian Ocean Territory', region: 'asiaAndPacific'},
  bn: {value: 'BN', label: 'Brunei Darussalam', region: 'asiaAndPacific'},
  bg: {value: 'BG', label: 'Bulgaria', region: 'europe'},
  bf: {value: 'BF', label: 'Burkina Faso', region: 'africa'},
  bi: {value: 'BI', label: 'Burundi', region: 'africa'},
  kh: {value: 'KH', label: 'Cambodia', region: 'asiaAndPacific'},
  cm: {value: 'CM', label: 'Cameroon', region: 'africa'},
  ca: {value: 'CA', label: 'Canada', region: 'northAmerica'},
  cv: {value: 'CV', label: 'Cape Verde', region: 'africa'},
  ky: {value: 'KY', label: 'Cayman Islands', region: 'southLatinAmerica'},
  cf: {value: 'CF', label: 'Central African Republic', region: 'africa'},
  td: {value: 'TD', label: 'Chad', region: 'africa'},
  cl: {value: 'CL', label: 'Chile', region: 'southLatinAmerica'},
  cn: {value: 'CN', label: 'China', region: 'asiaAndPacific'},
  cx: {value: 'CX', label: 'Christmas Island', region: 'asiaAndPacific'},
  cc: {value: 'CC', label: 'Cocos (Keeling) Islands', region: 'asiaAndPacific'},
  co: {value: 'CO', label: 'Colombia', currency: 'COP', region: 'southLatinAmerica'},
  km: {value: 'KM', label: 'Comoros', region: 'arabStates'},
  cg: {value: 'CG', label: 'Congo', region: 'africa'},
  cd: {value: 'CD', label: 'Congo, Democratic Republic'},
  ck: {value: 'CK', label: 'Cook Islands', region: 'asiaAndPacific'},
  cr: {value: 'CR', label: 'Costa Rica', region: 'southLatinAmerica'},
  ci: {value: 'CI', label: "Cote D'Ivoire", forbidden: true},
  hr: {value: 'HR', label: 'Croatia', region: 'europe'},
  cu: {value: 'CU', label: 'Cuba', region: 'southLatinAmerica'},
  cy: {value: 'CY', label: 'Cyprus', currency: 'EUR', region: 'europe'},
  cz: {value: 'CZ', label: 'Czech Republic', region: 'europe'},
  dk: {value: 'DK', label: 'Denmark', region: 'europe'},
  dj: {value: 'DJ', label: 'Djibouti', region: 'arabStates'},
  dm: {value: 'DM', label: 'Dominica', region: 'southLatinAmerica'},
  do: {value: 'DO', label: 'Dominican Republic', region: 'southLatinAmerica'},
  ec: {value: 'EC', label: 'Ecuador', region: 'southLatinAmerica'},
  eg: {value: 'EG', label: 'Egypt', region: 'arabStates'},
  sv: {value: 'SV', label: 'El Salvador', region: 'southLatinAmerica'},
  gq: {value: 'GQ', label: 'Equatorial Guinea', region: 'africa'},
  er: {value: 'ER', label: 'Eritrea', region: 'africa'},
  ee: {value: 'EE', label: 'Estonia', region: 'europe'},
  et: {value: 'ET', label: 'Ethiopia', region: 'africa'},
  fk: {value: 'FK', label: 'Falkland Islands (Malvinas)', region: 'southLatinAmerica'},
  fo: {value: 'FO', label: 'Faroe Islands', region: 'europe'},
  fj: {value: 'FJ', label: 'Fiji', region: 'asiaAndPacific'},
  fi: {value: 'FI', label: 'Finland', region: 'europe'},
  fr: {value: 'FR', label: 'France', region: 'europe'},
  gf: {value: 'GF', label: 'French Guiana', region: 'southLatinAmerica'},
  pf: {value: 'PF', label: 'French Polynesia', region: 'asiaAndPacific'},
  tf: {value: 'TF', label: 'French Southern Territories', region: 'asiaAndPacific'},
  ga: {value: 'GA', label: 'Gabon', region: 'africa'},
  gm: {value: 'GM', label: 'Gambia', region: 'africa'},
  ge: {value: 'GE', label: 'Georgia', region: 'europe'},
  de: {value: 'DE', label: 'Germany', region: 'europe'},
  gh: {value: 'GH', label: 'Ghana', region: 'africa'},
  gi: {value: 'GI', label: 'Gibraltar', region: 'europe'},
  gr: {value: 'GR', label: 'Greece', region: 'europe'},
  gl: {value: 'GL', label: 'Greenland', region: 'europe'},
  gd: {value: 'GD', label: 'Grenada', region: 'southLatinAmerica'},
  gp: {value: 'GP', label: 'Guadeloupe', region: 'southLatinAmerica'},
  gu: {value: 'GU', label: 'Guam', region: 'asiaAndPacific'},
  gt: {value: 'GT', label: 'Guatemala', region: 'southLatinAmerica'},
  gg: {value: 'GG', label: 'Guernsey', region: 'europe'},
  gn: {value: 'GN', label: 'Guinea', region: 'africa'},
  gw: {value: 'GW', label: 'Guinea-Bissau', region: 'africa'},
  gy: {value: 'GY', label: 'Guyana', forbidden: true, region: 'southLatinAmerica'},
  ht: {value: 'HT', label: 'Haiti', region: 'southLatinAmerica'},
  hm: {value: 'HM', label: 'Heard Island & Mcdonald Islands'},
  va: {value: 'VA', label: 'Holy See (Vatican City State)', region: 'europe'},
  hn: {value: 'HN', label: 'Honduras', region: 'southLatinAmerica'},
  hk: {value: 'HK', label: 'Hong Kong', region: 'asiaAndPacific'},
  hu: {value: 'HU', label: 'Hungary', region: 'europe'},
  is: {value: 'IS', label: 'Iceland', region: 'europe'},
  in: {value: 'IN', label: 'India', region: 'asiaAndPacific'},
  id: {value: 'ID', label: 'Indonesia', region: 'asiaAndPacific'},
  ir: {value: 'IR', label: 'Iran, Islamic Republic Of', region: 'asiaAndPacific', forbidden: false},
  iq: {value: 'IQ', label: 'Iraq', forbidden: true, region: 'arabStates'},
  ie: {value: 'IE', label: 'Ireland', region: 'europe'},
  im: {value: 'IM', label: 'Isle Of Man'},
  il: {value: 'IL', label: 'Israel', region: 'europe'},
  it: {value: 'IT', label: 'Italy', region: 'europe'},
  jm: {value: 'JM', label: 'Jamaica', region: 'southLatinAmerica'},
  jp: {value: 'JP', label: 'Japan', region: 'asiaAndPacific'},
  je: {value: 'JE', label: 'Jersey', region: 'europe'},
  jo: {value: 'JO', label: 'Jordan', region: 'arabStates'},
  kz: {value: 'KZ', label: 'Kazakhstan', region: 'asiaAndPacific'},
  ke: {value: 'KE', label: 'Kenya', region: 'africa'},
  ki: {value: 'KI', label: 'Kiribati', region: 'asiaAndPacific'},
  kr: {value: 'KR', label: 'Korea, Republic Of', region: 'asiaAndPacific'},
  kv: {value: 'KV', label: 'Kosovo'},
  kw: {value: 'KW', label: 'Kuwait', region: 'arabStates'},
  kg: {value: 'KG', label: 'Kyrgyzstan', region: 'asiaAndPacific'},
  la: {value: 'LA', label: 'Lao People\'s Democratic Republic', forbidden: true, region: 'asiaAndPacific'},
  lv: {value: 'LV', label: 'Latvia', region: 'europe'},
  lb: {value: 'LB', label: 'Lebanon', region: 'arabStates'},
  ls: {value: 'LS', label: 'Lesotho', region: 'africa'},
  lr: {value: 'LR', label: 'Liberia', region: 'africa'},
  ly: {value: 'LY', label: 'Libyan Arab Jamahiriya', region: 'arabStates'},
  li: {value: 'LI', label: 'Liechtenstein', region: 'europe'},
  lt: {value: 'LT', label: 'Lithuania', region: 'europe'},
  lu: {value: 'LU', label: 'Luxembourg', region: 'europe'},
  mo: {value: 'MO', label: 'Macao', region: 'asiaAndPacific'},
  mk: {value: 'MK', label: 'Macedonia', region: 'europe'},
  mg: {value: 'MG', label: 'Madagascar', region: 'africa'},
  mw: {value: 'MW', label: 'Malawi', region: 'africa'},
  my: {value: 'MY', label: 'Malaysia', region: 'asiaAndPacific'},
  mv: {value: 'MV', label: 'Maldives', region: 'asiaAndPacific'},
  ml: {value: 'ML', label: 'Mali', region: 'africa'},
  mt: {value: 'MT', label: 'Malta', region: 'europe'},
  mh: {value: 'MH', label: 'Marshall Islands', region: 'asiaAndPacific'},
  mq: {value: 'MQ', label: 'Martinique', region: 'southLatinAmerica'},
  mr: {value: 'MR', label: 'Mauritania', region: 'arabStates'},
  mu: {value: 'MU', label: 'Mauritius', region: 'africa'},
  yt: {value: 'YT', label: 'Mayotte', region: 'africa'},
  mx: {value: 'MX', label: 'Mexico', region: 'southLatinAmerica'},
  fm: {value: 'FM', label: 'Micronesia, Federated States Of'},
  md: {value: 'MD', label: 'Moldova', region: 'europe'},
  mc: {value: 'MC', label: 'Monaco', region: 'europe'},
  mn: {value: 'MN', label: 'Mongolia', region: 'asiaAndPacific'},
  me: {value: 'ME', label: 'Montenegro', region: 'europe'},
  ms: {value: 'MS', label: 'Montserrat', region: 'southLatinAmerica'},
  ma: {value: 'MA', label: 'Morocco', region: 'arabStates'},
  mz: {value: 'MZ', label: 'Mozambique', region: 'africa'},
  mm: {value: 'MM', label: 'Myanmar', forbidden: true, region: 'asiaAndPacific'},
  na: {value: 'NA', label: 'Namibia', region: 'africa'},
  nr: {value: 'NR', label: 'Nauru', region: 'asiaAndPacific'},
  np: {value: 'NP', label: 'Nepal', region: 'asiaAndPacific'},
  nl: {value: 'NL', label: 'Netherlands', region: 'europe'},
  an: {value: 'AN', label: 'Netherlands Antilles', region: 'southLatinAmerica'},
  nc: {value: 'NC', label: 'New Caledonia', region: 'asiaAndPacific'},
  nz: {value: 'NZ', label: 'New Zealand', region: 'asiaAndPacific'},
  ni: {value: 'NI', label: 'Nicaragua', region: 'southLatinAmerica'},
  ne: {value: 'NE', label: 'Niger', region: 'africa'},
  ng: {value: 'NG', label: 'Nigeria', region: 'africa'},
  nu: {value: 'NU', label: 'Niue', region: 'asiaAndPacific'},
  nf: {value: 'NF', label: 'Norfolk Island', region: 'asiaAndPacific'},
  mp: {value: 'MP', label: 'Northern Mariana Islands', region: 'asiaAndPacific'},
  no: {value: 'NO', label: 'Norway', region: 'europe'},
  om: {value: 'OM', label: 'Oman', region: 'arabStates'},
  pk: {value: 'PK', label: 'Pakistan', region: 'asiaAndPacific'},
  pw: {value: 'PW', label: 'Palau', region: 'asiaAndPacific'},
  ps: {value: 'PS', label: 'Palestinian Territory, Occupied'},
  pa: {value: 'PA', label: 'Panama', region: 'southLatinAmerica'},
  pg: {value: 'PG', label: 'Papua New Guinea', forbidden: true, region: 'asiaAndPacific'},
  py: {value: 'PY', label: 'Paraguay', region: 'southLatinAmerica'},
  pe: {value: 'PE', label: 'Peru', region: 'southLatinAmerica'},
  ph: {value: 'PH', label: 'Philippines', region: 'asiaAndPacific'},
  pn: {value: 'PN', label: 'Pitcairn'},
  pl: {value: 'PL', label: 'Poland', region: 'europe'},
  pt: {value: 'PT', label: 'Portugal', region: 'europe'},
  pr: {value: 'PR', label: 'Puerto Rico', region: 'southLatinAmerica'},
  qa: {value: 'QA', label: 'Qatar', region: 'arabStates'},
  re: {value: 'RE', label: 'Reunion', region: 'asiaAndPacific'},
  ro: {value: 'RO', label: 'Romania', region: 'europe'},
  ru: {value: 'RU', label: 'Russian Federation', region: 'europe'},
  rw: {value: 'RW', label: 'Rwanda', region: 'africa'},
  bl: {value: 'BL', label: 'Saint Barthelemy', region: 'southLatinAmerica'},
  sh: {value: 'SH', label: 'Saint Helena', region: 'africa'},
  kn: {value: 'KN', label: 'Saint Kitts And Nevis'},
  lc: {value: 'LC', label: 'Saint Lucia', region: 'southLatinAmerica'},
  mf: {value: 'MF', label: 'Saint Martin', region: 'southLatinAmerica'},
  pm: {value: 'PM', label: 'Saint Pierre And Miquelon'},
  vc: {value: 'VC', label: 'Saint Vincent And Grenadines'},
  ws: {value: 'WS', label: 'Samoa', region: 'asiaAndPacific'},
  sm: {value: 'SM', label: 'San Marino', region: 'europe'},
  st: {value: 'ST', label: 'Sao Tome And Principe'},
  sa: {value: 'SA', label: 'Saudi Arabia', region: 'arabStates'},
  sn: {value: 'SN', label: 'Senegal', region: 'africa'},
  rs: {value: 'RS', label: 'Serbia', region: 'europe'},
  sc: {value: 'SC', label: 'Seychelles', region: 'africa'},
  sl: {value: 'SL', label: 'Sierra Leone', region: 'africa'},
  sg: {value: 'SG', label: 'Singapore', region: 'asiaAndPacific'},
  sk: {value: 'SK', label: 'Slovakia', region: 'europe'},
  si: {value: 'SI', label: 'Slovenia', region: 'europe'},
  sb: {value: 'SB', label: 'Solomon Islands', region: 'asiaAndPacific'},
  so: {value: 'SO', label: 'Somalia', region: 'arabStates'},
  za: {value: 'ZA', label: 'South Africa', region: 'africa'},
  gs: {value: 'GS', label: 'South Georgia And Sandwich Isl.'},
  es: {value: 'ES', label: 'Spain', region: 'europe'},
  lk: {value: 'LK', label: 'Sri Lanka', region: 'asiaAndPacific'},
  sd: {value: 'SD', label: 'Sudan', forbidden: true, region: 'arabStates'},
  sr: {value: 'SR', label: 'Suriname', region: 'southLatinAmerica'},
  sj: {value: 'SJ', label: 'Svalbard And Jan Mayen'},
  sz: {value: 'SZ', label: 'Swaziland', region: 'africa'},
  se: {value: 'SE', label: 'Sweden', region: 'europe'},
  ch: {value: 'CH', label: 'Switzerland', region: 'europe'},
  sy: {value: 'SY', label: 'Syrian Arab Republic', forbidden: true, region: 'asiaAndPacific'},
  tw: {value: 'TW', label: 'Taiwan', region: 'asiaAndPacific'},
  tj: {value: 'TJ', label: 'Tajikistan', region: 'asiaAndPacific'},
  tz: {value: 'TZ', label: 'Tanzania', region: 'africa'},
  th: {value: 'TH', label: 'Thailand', region: 'asiaAndPacific'},
  tl: {value: 'TL', label: 'Timor-Leste', region: 'asiaAndPacific'},
  tg: {value: 'TG', label: 'Togo', region: 'africa'},
  tk: {value: 'TK', label: 'Tokelau', region: 'asiaAndPacific'},
  to: {value: 'TO', label: 'Tonga', region: 'asiaAndPacific'},
  tt: {value: 'TT', label: 'Trinidad And Tobago'},
  tn: {value: 'TN', label: 'Tunisia', region: 'arabStates'},
  tr: {value: 'TR', label: 'Turkey', region: 'europe'},
  tm: {value: 'TM', label: 'Turkmenistan', region: 'asiaAndPacific'},
  tc: {value: 'TC', label: 'Turks And Caicos Islands'},
  tv: {value: 'TV', label: 'Tuvalu', region: 'asiaAndPacific'},
  ug: {value: 'UG', label: 'Uganda', forbidden: true, region: 'africa'},
  ua: {value: 'UA', label: 'Ukraine', forbidden: true, region: 'europe'},
  ae: {value: 'AE', label: 'United Arab Emirates', region: 'arabStates'},
  gb: {value: 'GB', label: 'United Kingdom', region: 'europe'},
  us: {value: 'US', label: 'United States', forbidden: true, region: 'northAmerica'},
  um: {value: 'UM', label: 'United States Outlying Islands', forbidden: true},
  uy: {value: 'UY', label: 'Uruguay', region: 'southLatinAmerica'},
  uz: {value: 'UZ', label: 'Uzbekistan', region: 'asiaAndPacific'},
  vu: {value: 'VU', label: 'Vanuatu', forbidden: true, region: 'asiaAndPacific'},
  ve: {value: 'VE', label: 'Venezuela', region: 'southLatinAmerica'},
  vn: {value: 'VN', label: 'Viet Nam'},
  vg: {value: 'VG', label: 'Virgin Islands, British', region: 'southLatinAmerica'},
  vi: {value: 'VI', label: 'Virgin Islands, U.S.', region: 'southLatinAmerica', forbidden: true},
  wf: {value: 'WF', label: 'Wallis And Futuna'},
  eh: {value: 'EH', label: 'Western Sahara', region: 'africa'},
  ye: {value: 'YE', label: 'Yemen', forbidden: true, region: 'arabStates'},
  zm: {value: 'ZM', label: 'Zambia', region: 'africa'},
  zw: {value: 'ZW', label: 'Zimbabwe', region: 'africa'},
}))

export {countries}
