name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/Resilisense-FE/ && echo "Directory changed to /home/ubuntu/Resilisense-FE" || echo "Failed to change directory"
            git add . && git commit -m "Committing uncommitted changes" || echo "No changes to commit"
            git pull origin main && echo "Git pull successful" || echo "Git pull failed"
            npm install --force > /dev/null 2>&1 && echo "NPM install successful" || echo "NPM install failed"
            pm2 restart Resilisense-FE > /dev/null 2>&1 && echo "PM2 restarted successfully" || echo "PM2 restart failed"
            echo "======END======"
